import Head from 'next/head'
import Image from 'next/image'

import React, { useEffect, useState } from "react"
import cookieCutter from "cookie-cutter"
import { v4 as uuidv4 } from 'uuid';
import Cookies from 'cookies'

import Nav from "./../components/Nav"
import FilterList from "./../components/FilterList"

const Home = () => {
  const [cartItems, setCartItems] = useState([])

  useEffect(() => {
    if (!cartItems.length > 0) {
      var id = cookieCutter.get('cartid')

      if (id !== undefined) {
        fetch(process.env.NEXT_PUBLIC_WEB_SERVER + "/carts/" + id)
          .then(async res => {
            if (res.status == 401) {
              const newUuid = uuidv4();
  
              fetch(process.env.NEXT_PUBLIC_WEB_SERVER + "/carts/", {
                method: "POST",
                headers: {
                  "Content-type": "application/json",
                },
                body: JSON.stringify({
                  id: newUuid
                })
              }).then((res) => {
                if (res.ok) {
                  cookieCutter.set('cartid', newUuid) 
                }
              })
            } else {
              var json = await res.json()                    
              setCartItems(json.content)
            }
          })
      }
    }
    
  }, [])

  return (
    <div>
      <Head>
        <title>Knudsen Krudt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav cartItems={cartItems}/>

      <main className="bg-white max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <FilterList cartItems={cartItems} setCartItems={setCartItems} />
      </main>
    </div>
  )
}

Home.getInitialProps = ({req, res}) => {
  const cookies = new Cookies(req, res)

  var id = cookies.get('cartid')
  
  if (id) return;
  const newUuid = uuidv4();

  console.log("BEFORE FETCHING")
  fetch(process.env.NEXT_PUBLIC_WEB_SERVER + "/carts/", {
    method: "POST",
    headers: {
      "Content-type": "application/json",
    },
    body: JSON.stringify({
      id: newUuid
    })
  }).then((res) => {
    console.log("COOKIE SET ATTEMPT")
    if (res.ok) {
      cookies.set('cartid', newUuid, {
        httpOnly: false
      }) 
    }
  })
}

export default Home